// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/history": {
            "get": {
                "description": "Belirtilen IP adresinin hangi endpoint'e kaç istek attığını ve aldığı durum kodlarını listeler.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analitik"
                ],
                "summary": "IP Geçmiş Analitiği Sorgulama",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sorgulanacak IP Adresi (Örn: 127.0.0.1)",
                        "name": "ip",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Başarılı Rapor Çıktısı",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Eksik parametre hatası",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Veritabanı sorgu hatası",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Rate Limiter API",
	Description:      "Go, Redis ve PostgreSQL ile geliştirilmiş gelişmiş Rate Limiter projesi.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
