basePath: /
host: localhost:8080
info:
  contact: {}
  description: Go, Redis ve PostgreSQL ile geliştirilmiş gelişmiş Rate Limiter projesi.
  title: Rate Limiter API
  version: "1.0"
paths: {}
swagger: "2.0"
